server:
  port: 8088

#mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      table-underline: true
      db-type: mysql
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/*.xml

#数据源
spring:
  datasource:
    # 配置数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://139.224.129.156:3306/act?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: 520xujiafei

#日志
logging:
  config: classpath:logback-spring.xml
  level:
    # 日志级别 debug-> info -> warning -> error
    # 默认级别为 info
    # 如果设置了debug=true的时候，日志级别会自动降低为debug

    # ROOT代表默认全局设置
    ROOT: INFO
    org:
      # 可以设置指定包的输出级别,这样的话，指定的包，级别以下的日志就不在打印或者写入日志文件
      apache: ERROR
      springframework: ERROR
  file:
    # 日志输出的地址：Spring Boot默认并没有进行文件输出，只在控制台中进行了打印
    name: /log


